### ISSUE TITLE
Add functions monthpicker and yearpicker

### ISSUE THREAD

**Issue by BeejeeDS** [silverskater/jQuery-UI-Datepicker-MonthYearPicker-Addon#7]
This isn't realy an issue more a request (didn't know where else to put this).

Wouldn't it be possible to extend this addon to allow users to call $('meh').monthpicker().
This will then go to the monthview where the user can select the month.
This value will then be pushed to the input (ex. 05/2015) using the default datepicker code.
The same could be done with $('meh').yearpicker().

I had some projects in the past where the client needed a monthpicker.
I used another plugin then but yours is far superior because you make use of the default datepicker.

I would do this myself but this kind of changes is way beyond my javascript skills.
I don't think this would require too much changes though.

**Comment by Daijobou** [comment]
Here a alternate monthpicker https://github.com/KidSysco/jquery-ui-month-picker
