### ISSUE TITLE
Back to start [Feature-Request]

### ISSUE THREAD

**Issue by Daijobou** [silverskater/jQuery-UI-Datepicker-MonthYearPicker-Addon#8]
Great Addon! I love it. Can you add in the last step click on year, go back to day overview?

* Click on "August 2015" => Month overview for 2015
* Click on "2015" => Year overview "2010 - 2019"
* Click on "2010 - 2019" go back to day overview << Feature-Request

Like this version http://stefangabos.ro/jquery/zebra-datepicker/ (not working with IE11)

**Comment by silverskater** [comment]
Thank you, Daijobou for the suggestion. The feature was added, original pull request: https://github.com/silverskater/jQuery-UI-Datepicker-MonthYearPicker-Addon/commit/15b406ecaa47156f31c29009a553817777f75176. 
All credit goes to https://github.com/rongybika. Thank you. 
Check out the new master or tag v1.11.4.

**Comment by Daijobou** [comment]
Thank you. There is a little bug. You need return in onclick

'onclick="return $.backToActualMonth();" '

otherwise you jump to home => href="#" ;)

**Comment by silverskater** [comment]
Thank you Daijobou for your suggestion, and rongybika for implementing it.
